#!/usr/bin/env node
/**
 * Build step for Vercel (and local preview).
 * Injects Supabase environment variables into supabase-config.js
 * so the static site can read them at runtime.
 */

require('dotenv').config();

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const outputFile = path.join(root, 'supabase-config.js');

const url = process.env.SUPABASE_URL || '__SUPABASE_URL__';
const key = process.env.SUPABASE_ANON_KEY || '__SUPABASE_ANON_KEY__';
const projectId = process.env.SUPABASE_PROJECT_ID || '__SUPABASE_PROJECT_ID__';

const content = `// Auto-generated by scripts/build.js — do not edit manually.
// This file is overwritten at build time from Vercel environment variables.
(function () {
    'use strict';
    const env = window.ENV || {};
    window.SUPABASE_CONFIG = {
        SUPABASE_URL: env.SUPABASE_URL || '${url.replace(/'/g, "\\'")}',
        SUPABASE_ANON_KEY: env.SUPABASE_ANON_KEY || '${key.replace(/'/g, "\\'")}',
        SUPABASE_PROJECT_ID: env.SUPABASE_PROJECT_ID || '${projectId.replace(/'/g, "\\'")}'
    };
})();
`;

fs.writeFileSync(outputFile, content, 'utf8');
console.log('Generated supabase-config.js with environment variables.');
